name: Android Build And Publish

on: 
  push:
    branches: 
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
   
    - name: Create Artifacts
      run: ./gradlew install
      
    - name: Publish To Bintray
      run: ./gradlew bintrayUpload
